### ISSUE TITLE
输出结果该怎么解释呢？

### ISSUE THREAD

**Issue by xiahui625649** [chaoning/GMAT#1]
宁老师好，我照着示例运行了一边代码，但是发现生成的结果文件里很多没有表头信息，没办法理解具体含义？例如不平衡纵向数据GWAS结果列蛋这些文件：test2.0_11833.res  test2.ai_mat test2.em_mat test2.fd_mat test2.wemai_mat，它们的输出内容具体是啥意思，该怎么解释呢？能不能简单写个输出结果注释文件，这样或许对像我这样初次接触该软件的小白更友好，也有利于该软件的推广应用，谢谢！

**Comment by chaoning** [comment]
感谢对软件的关注，目前软件刚刚完成，说明书还需要继续完善。test2.0_11833.res是主要的结果文件，order chro snp_id cm base allele0 allele1是snp信息；cc_par和cc_gra表示方差组分收敛标准，不平衡数据无法实现每个snp估计方差组分，该值为1000，没有意义； eff*表示不同阶数勒让德多项式系数值，可以用来拟合snp效应曲线；eff_var*表示对应系数估计值的方差；p是显著性p值。该文件重点关注p值和eff*即可。
test2.ai_mat，test2.em_mat，test2.fd_mat，test2.wemai_mat，分别是ai信息阵、em信息阵、一阶偏导向量、EM和AI加权阵，这几个文件对用户意义不大，可以忽略。
tes2.var表示方差组分估计的结果，和DMU软件输出格式一样。
有问题，欢迎随时提出。
