### ISSUE TITLE
一些关于GMAT的问题

### ISSUE THREAD

**Issue by flystar233** [chaoning/GMAT#1]
1. 在 readme 第一个代码块中，Step 3 代码应该为 `print(var_com_a_axa)` 。
2. readme中没有说明示例代码中使用小鼠表型文件的每列是什么，以下是我的部分测试表型：
` > head -5 trait.txt`

 ` ID_1       ID_1 	-1.261850849964`
 ` ID_2	ID_2	 2.59372569418469`
 ` ID_3	ID_3 	2.91265183779147`
 ` ID_4	ID_4	 -0.404705122046798`
 ` ID_5	ID_5 	-9.81734634345145`

测试第一个代码块之后 `print(var_com_a_axa)` 可以得出：
`INFO:root:Variances converged.
[ 5.76178171  3.24184587 16.38953142]`
但是`remma_epiAA_cpu`函数无法运行，报错为：
`ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)`

**Comment by chaoning** [comment]
抱歉，最近一直忙其他事，说明书没有完善好。表型文件前两列分别是家系id和个体id要与plink文件保持一致，最后一列是表型值，中间是其他协变量，而且至少包含截距项（全为1），所以在表型前加一列1，可以解决问题。

**Comment by flystar233** [comment]
谢谢，表型加入截距1后，可以正常工作了~
对于结果文件 remma_epiAA_cpu， 是否可以使前2列 SNP位点的名字和变异文件中SNP名字一致，序号的话不方便查找。

**Comment by chaoning** [comment]
我加了额外的一步：
# Step 5: Select top SNPs and add the SNP position
from gmat.remma.annotation import annotation_snp_pos
res_file = 'remma_epiAA_cpu'  # result file
annotation_snp_pos(res_file, bed_file, p_cut=1.0e-7)
可以帮助筛选显著SNP，并加上SNP位置信息
注意要先将原来的卸载掉，安装更新后的
pip uninstall gmat # 卸载
pip install gmat # 安装
