### ISSUE TITLE
上位性检测时用--parallel参数会使检验的标记对减少吗？

### ISSUE THREAD

**Issue by qizhengyang2017** [chaoning/GMAT#2]
老师您好，
    在做上位性分析的时候，您推荐使用--parallel参数，我看这个参数的注释是将全基因组标记等分为total份,仅对第i份进行分析。那么使用这个参数的时候，第i份里的标记会和第i+1份里的标记做上位性检测吗？如果不会检测的话，用--parallel参数获得的互作的SNP对就会比真实的少了。

我用您软件中的mouse数据集测试，不加--prallel参数输出了272对显著的互作
```
remma --epis abya --bfile plink --data pheno --grm test.agrm.id_fmt,test.aagrm.id_fmt --class sex,treat --covar age --trait trait --continue --maxiter 0 --out test
```

而用了--paralle参数只获得了212对互作
```
remma --epis abya --bfile plink --data pheno --grm test.agrm.id_fmt,test.aagrm.id_fmt --class sex,treat --covar age --trait trait --continue --maxiter 0 --out test --parallel 1,3
remma --epis abya --bfile plink --data pheno --grm test.agrm.id_fmt,test.aagrm.id_fmt --class sex,treat --covar age --trait trait --continue --maxiter 0 --out test --parallel 2,3
remma --epis abya --bfile plink --data pheno --grm test.agrm.id_fmt,test.aagrm.id_fmt --class sex,treat --covar age --trait trait --continue --maxiter 0 --out test --parallel 3,3
```
看起了确实是加--parallel参数会使检测到的互作减少

**Comment by chaoning** [comment]
您好。第i份的标记会和第i+1份及后面的标记做上位检验。REMMA方法首先采用近似检验统计量对标记进行预筛，然后筛选出p值小于1.0e-4的互作对，重新利用精确方法计算p值。近似检验统计量的计算，有一定的随机性，不过差别很小，会导致加不加--parallel参数输出的结果个数有细微差别。如果加入--exact参数，全部互作对均用精确方法计算，两者输出的结果个数会完全一致。不过加入--exact参数后，计算效率会大幅度降低。另外输出的结果不是显著互作对，仅是p值小于1.0e-4的互作。

**Comment by qizhengyang2017** [comment]
非常感谢！
