### ISSUE TITLE
PCA群体结构怎么加入模型中？

### ISSUE THREAD

**Issue by xiahui625649** [chaoning/GMAT#3]
对于纵向性状GWAS，怎么加入群体结构呢？利用--covar PC1,PC2,PC3吗？

**Comment by chaoning** [comment]
是的

**Comment by xiahui625649** [comment]
对于非平衡纵向GWAS的输入文件PCA也是一列一个吗？ID, Time,Trait,PC1,PC2,PC3这样吗？



At 2022-01-18 16:50:42, "chaoning" ***@***.***> wrote:

是的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chaoning** [comment]
是的，非平衡数据不同时间点的测量值放在同一列，放PCA的时候对应个体重复出现

**Comment by chaoning** [comment]
是的，非平衡数据不同时间点的测量值放在同一列，放PCA的时候对应个体重复出现
